name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: Install an SSL
      run: apt-get -qq update && apt-get -qq install -y libssl1.1 libssl-dev openssl

    - name: Install a newer zef
      run:  zef install --force-install --/test https://github.com/ugexe/zef.git

    - name: Install Test::Meta
      run:  zef install --force-install --/test Test::META

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
