name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: jjmerelo/alpine-raku:gha-2021.10

    steps:
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: install an ssl
      run: apk add libssl-dev

    - name: Install a newer zef
      run:  zef install --force-install --/test https://github.com/ugexe/zef.git

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
